use crate::core::color::Color;
use crate::core::blend_mode::BlendMode;
use crate::core::animation::timeline::{TimelineProperty, CurveType};
use crate::app::state::ToolType;
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResizeAnchor {
    TopLeft,    TopCenter,    TopRight,
    MiddleLeft, Center,       MiddleRight,
    BottomLeft, BottomCenter, BottomRight,
}
#[derive(Debug, Clone, PartialEq)]
pub enum AppCommand {
    AddColorToPalette(Color),
    RemovePaletteColor(usize),
    SetPrimaryColor(Color),
    ToggleLayerLock(String),
    SetLayerOpacity(String, u8),
    MoveLayerUp(String),
    MoveLayerDown(String),
    RenameLayer(String, String),
    SetLayerBlendMode(String, BlendMode),
    ImportPalette,
    ExportPalette,
    SetPalette(crate::core::palette::Palette),
    ClearSelection,
    InvertSelection,
    StrokeSelection(u32),
    DuplicateLayer(String),
    MergeSelected(Vec<String>),
    MoveLayerToIndex(String, usize),

    WindowDrag,
    RequestExit,
    ConfirmExit,
    CancelExit,
    WindowClose,
    WindowMinimize,
    WindowMaximize,
    SaveProject,
    LoadProject,
    ImportImage,
    ExportPng,
    Undo,
    Redo,
    ResizeCanvas(u32, u32, ResizeAnchor),
    CommitCurrentTool,
    CancelCurrentTool,
    SetLanguage(String),
    PenFill,
    PenStroke,
    CreateAnimation(String),
    SelectAnimation(String),
    DeleteKeyframe(String, Option<TimelineProperty>, f32),
    UpdateKeyframeCurve(String, TimelineProperty, f32, CurveType),
    MoveSelectedKeyframes(f32),
    ApplySpineOffset { mode: usize, fixed_frames: i32, step_frames: i32 },
    ChangeBrushSize(i32),
    SelectTool(ToolType),
    TogglePathNodeType(usize),
    DeletePathNode(usize),
    ToggleTransformCoordinateSystem,
    InsertManualKeyframe(String),
    TogglePlayback,
    StepFrame(i32),
    SetTime(f32),
    SetPlaybackSpeed(f32),
    ToggleLoop,
    ToggleTimelineFilter(TimelineProperty),
}